"""empty message



Revision ID: 8be8963fb0f3

Revises: 349a068d240c

Create Date: 2018-02-27 23:47:47.468946



"""

from alembic import op

import sqlalchemy as sa





# revision identifiers, used by Alembic.

revision = '8be8963fb0f3'

down_revision = '349a068d240c'

branch_labels = None

depends_on = None





def upgrade():

    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('user_profile', sa.Column('password', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###





def downgrade():

    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('user_profile', 'password')

    # ### end Alembic commands ###