"""empty message

Revision ID: c7d48d4a6902
Revises: 8be8963fb0f3
Create Date: 2018-03-11 22:04:20.484048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7d48d4a6902'
down_revision = '8be8963fb0f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('biography', sa.Text(), nullable=True))
    op.add_column('user_profile', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('user_profile', sa.Column('email', sa.String(length=80), nullable=True))
    op.add_column('user_profile', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('user_profile', sa.Column('location', sa.String(length=80), nullable=True))
    op.add_column('user_profile', sa.Column('photo_name', sa.String(length=80), nullable=True))
    op.drop_constraint(u'user_profile_username_key', 'user_profile', type_='unique')
    op.create_unique_constraint(None, 'user_profile', ['email'])
    op.drop_column('user_profile', 'username')
    op.drop_column('user_profile', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('password', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('user_profile', sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_profile', type_='unique')
    op.create_unique_constraint(u'user_profile_username_key', 'user_profile', ['username'])
    op.drop_column('user_profile', 'photo_name')
    op.drop_column('user_profile', 'location')
    op.drop_column('user_profile', 'gender')
    op.drop_column('user_profile', 'email')
    op.drop_column('user_profile', 'date_created')
    op.drop_column('user_profile', 'biography')
    # ### end Alembic commands ###
